// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJ709fFb5_dNJJsPEP4aG19dupohs2d8',
    appId: '1:223996902433:web:0b8fc853d3041d4560f760',
    messagingSenderId: '223996902433',
    projectId: 'rawapp-d934c',
    authDomain: 'rawapp-d934c.firebaseapp.com',
    storageBucket: 'rawapp-d934c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_3XTH8MmJaFPlRUNZ-mnDkg9U9-NI-4w',
    appId: '1:223996902433:android:ce7d88ce70c164ac60f760',
    messagingSenderId: '223996902433',
    projectId: 'rawapp-d934c',
    storageBucket: 'rawapp-d934c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTcvUH2ce6kcJLJ9BuckFqKQsZLoY3mZ4',
    appId: '1:223996902433:ios:e740469f1a86dbc460f760',
    messagingSenderId: '223996902433',
    projectId: 'rawapp-d934c',
    storageBucket: 'rawapp-d934c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTcvUH2ce6kcJLJ9BuckFqKQsZLoY3mZ4',
    appId: '1:223996902433:ios:e740469f1a86dbc460f760',
    messagingSenderId: '223996902433',
    projectId: 'rawapp-d934c',
    storageBucket: 'rawapp-d934c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvJ709fFb5_dNJJsPEP4aG19dupohs2d8',
    appId: '1:223996902433:web:5cbb087c68e872d960f760',
    messagingSenderId: '223996902433',
    projectId: 'rawapp-d934c',
    authDomain: 'rawapp-d934c.firebaseapp.com',
    storageBucket: 'rawapp-d934c.firebasestorage.app',
  );
}
